### ISSUE TITLE
在header加上社徽

### ISSUE THREAD

**Issue by requiemformemories** [NTUOSC/ntuosc.github.io#3]
![0825-3](https://cloud.githubusercontent.com/assets/5207631/17958197/5da87486-6aca-11e6-971c-36832d13f8d8.png)
把圖中紅色的位置改成社徽
然後社徽目前應該會是這個: https://drive.google.com/file/d/0B2AHE58c_LJCc2lBcjE1aFdFTFk/view?usp=sharing

**Comment by lili668668** [comment]
替換掉了
